branches:
  only:
    - master
#    - next
  
language: erlang
otp_release:
   - 18.1
   - 18.2.1

node_js:
   - '6'

sudo: false

addons:
  apt:
    packages:
      - python-pycurl

install:
  - "make"

script:
  - "make tests"

notifications:
  email:
    on_success: change
    on_failure: always
