branches:
  only:
    - master
    - next
  
language: erlang
otp_release:
   - 17.0-rc1
   - R16B03-1
   - R16B03
   - R16B02
   - R16B01
   - R15B03
   - R15B02
   - R15B01
   - R14B04
   - R14B03
   - R14B02

install:
  - "sudo apt-get install libssl-dev libxml2-dev libexpat1-dev"
  - "rebar get-deps"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
