branches:
  only:
    - master
#    - next
  
language: erlang
otp_release:
   - 18.0
   - 18.1

sudo: false

addons:
  apt:
    packages:
      - python-pycurl
      - python-setuptools

install:
  - "make"

script:
  - "make tests"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
