branches:
  only:
    - master
#    - next
  
language: erlang
otp_release:
   - 18.0
   - 18.1

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libexpat1-dev
      - python-pycurl
      - python-setuptools

install:
  - "./bootstrap"
  - "make"

build:
  - "make test"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
