branches:
  only:
    - master
#    - next
  
language: erlang
otp_release:
   - 18.0

before_install:
  - "sudo apt-get update && sudo apt-get install build-essential libssl-dev libexpat1-dev"
  - "./bootstrap"

install:
  - "make"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
