branches:
  only:
    - master
#    - next
  
language: erlang
otp_release:
   - 18.1
   - 18.2.1

sudo: false

addons:
  apt:
    packages:
      - python-pycurl

before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install 6
  - node --version

install:
  - "make"

script:
  - "make tests"

notifications:
  email:
    on_success: change
    on_failure: always
